#!/bin/bash

. /opt/helpers

ISSET_ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS:+<set via env variable>}

export ICINGAWEB2_ADMIN_USER=${ICINGAWEB2_ADMIN_USER:-"icingaadmin"}
export ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS:-"icinga"}
export ICINGAWEB2_ADMIN_PASS_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASS}")


export DEFAULT_MYSQL_HOST=${DEFAULT_MYSQL_HOST:-mysql}
export DEFAULT_MYSQL_PORT=${DEFAULT_MYSQL_PORT:-3306}
export DEFAULT_MYSQL_USER=${DEFAULT_MYSQL_USER:-icinga2}
export DEFAULT_MYSQL_PASS=${DEFAULT_MYSQL_PASS:-$(pwgen -s 15 1)}

export MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}


export ICINGA2_FEATURE_DIRECTOR_PASS=${ICINGA2_FEATURE_DIRECTOR_PASS:-${DEFAULT_MYSQL_PASS}}

export ICINGA2_DB_MYSQL_HOST=${ICINGA2_DB_MYSQL_HOST:-${DEFAULT_MYSQL_HOST}}
export ICINGA2_DB_MYSQL_PORT=${ICINGA2_DB_MYSQL_PORT:-${DEFAULT_MYSQL_PORT}}
export ICINGA2_DB_MYSQL_USER=${ICINGA2_DB_MYSQL_USER:-icingadb}
export ICINGA2_DB_MYSQL_DATA=${ICINGA2_DB_MYSQL_DATA:-icingadb}
export ICINGA2_DB_MYSQL_PASS=${ICINGA2_DB_MYSQL_PASS:-${DEFAULT_MYSQL_PASS}}
export ICINGA2_DB_MYSQL_SKIP_DB_CREATION=${ICINGA2_DB_MYSQL_SKIP_DB_CREATION:-false}


# ido is not used TODO - remove these
export ICINGA2_IDO_MYSQL_HOST=${ICINGA2_IDO_MYSQL_HOST:-${DEFAULT_MYSQL_HOST}}
export ICINGA2_IDO_MYSQL_PORT=${ICINGA2_IDO_MYSQL_PORT:-${DEFAULT_MYSQL_PORT}}
export ICINGA2_IDO_MYSQL_USER=${ICINGA2_IDO_MYSQL_USER:-${DEFAULT_MYSQL_USER}}
export ICINGA2_IDO_MYSQL_PASS=${ICINGA2_IDO_MYSQL_PASS:-${IDO_PASSWORD:-${DEFAULT_MYSQL_PASS}}}
export ICINGA2_IDO_MYSQL_DATA=${ICINGA2_IDO_MYSQL_DATA:-icinga2idomysql}
export ICINGA2_IDO_MYSQL_SKIP_DB_CREATION=${ICINGA2_IDO_MYSQL_SKIP_DB_CREATION:-false}

export ICINGAWEB2_MYSQL_HOST=${ICINGAWEB2_MYSQL_HOST:-${DEFAULT_MYSQL_HOST}}
export ICINGAWEB2_MYSQL_PORT=${ICINGAWEB2_MYSQL_PORT:-${DEFAULT_MYSQL_PORT}}
export ICINGAWEB2_MYSQL_USER=${ICINGAWEB2_MYSQL_USER:-${DEFAULT_MYSQL_USER}}
export ICINGAWEB2_MYSQL_PASS=${ICINGAWEB2_MYSQL_PASS:-${ICINGAWEB2_PASSWORD:-${DEFAULT_MYSQL_PASS}}}
export ICINGAWEB2_MYSQL_DATA=${ICINGAWEB2_MYSQL_DATA:-icingaweb2}
export ICINGAWEB2_MYSQL_SKIP_DB_CREATION=${ICINGAWEB2_MYSQL_SKIP_DB_CREATION:-false}

export ICINGAWEB2_DIRECTOR_MYSQL_HOST=${ICINGAWEB2_DIRECTOR_MYSQL_HOST:-${DEFAULT_MYSQL_HOST}}
export ICINGAWEB2_DIRECTOR_MYSQL_PORT=${ICINGAWEB2_DIRECTOR_MYSQL_PORT:-${DEFAULT_MYSQL_PORT}}
export ICINGAWEB2_DIRECTOR_MYSQL_USER=${ICINGAWEB2_DIRECTOR_MYSQL_USER:-${DEFAULT_MYSQL_USER}}
export ICINGAWEB2_DIRECTOR_MYSQL_PASS=${ICINGAWEB2_DIRECTOR_MYSQL_PASS:-${DIRECTOR_PASSWORD:-${DEFAULT_MYSQL_PASS}}}
export ICINGAWEB2_DIRECTOR_MYSQL_DATA=${ICINGAWEB2_DIRECTOR_MYSQL_DATA:-icingaweb2_director}
export ICINGAWEB2_DIRECTOR_MYSQL_SKIP_DB_CREATION=${ICINGAWEB2_DIRECTOR_MYSQL_SKIP_DB_CREATION:-false}

# Generate the system wide locales in the background.
# It may take a long time, depending on the mounted /etc/locale.gen.
# The only part, where locale processing is known to be necessary, is
# the Icingaweb2 translation plugin and locale-gen should be finished
# until the first webpage is started.
locale-gen &

run-parts --lsbsysinit --exit-on-error -- /opt/setup

cat <<-END

===================================================================
MySQL user 'root' has no password but only allows local connections

$(
if evaluate_boolean "${ICINGA2_FEATURE_GRAPHITE}"; then
	echo "Graphite writer enabled and sending data to carbon agent at: ${ICINGA2_FEATURE_GRAPHITE_HOST}:${ICINGA2_FEATURE_GRAPHITE_PORT}"
fi
)

Icinga Web 2 (/icingaweb2) default credentials: ${ICINGAWEB2_ADMIN_USER}:${ISSET_ICINGAWEB2_ADMIN_PASS:-$ICINGAWEB2_ADMIN_PASS}
===================================================================

Starting Supervisor.
END

# remove local config

mkdir -p /etc/icinga2/archive
mv /etc/icinga2/conf.d/* /etc/icinga2/archive/
mv /etc/icinga2/archive/api-user*.conf /etc/icinga2/conf.d/

icinga2 daemon --validate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
supervisor_pid=$!  

# wait 40 seconds and then run extra scripts
(
  sleep 40
  # Place your script or command here
  echo "Supervisor has been running for 40 seconds, now executing script..."
  # extra onetime scripts to import data - need to be idempotent
  /opt/onetime/import-baskets
  python3 /opt/setup/onetime/director_api.py -s http://localhost -u ${ICINGAWEB2_ADMIN_USER} -p ${ICINGAWEB2_ADMIN_PASS}

  # Idempotent 
  STATUS_FILE="/opt/onetime/.netbox_import_done"

  if [ ! -f "$STATUS_FILE" ]; then
    echo "Running NetBox importer..."
    if python3 /opt/onetime/netbox-importer.py --url ${NETBOX_URL} --token ${NETBOX_APIKEY} --file /opt/onetime/netbox-data.json; then
      # Only create the file if the import was successful
      echo "NetBox import successful, marking as done."
      touch "$STATUS_FILE"
    else
      echo "NetBox import failed, not marking as done."
    fi
  else
    echo "NetBox import already done, skipping."
  fi
) &

# Trap SIGTERM to gracefully shut down supervisord
trap "supervisorctl shutdown && wait $supervisor_pid" SIGTERM

wait $supervisor_pid  

