services:
  icinga2:
    image: sol1/icinga2-stack
      #build:
      #context: ./
      #dockerfile: Dockerfile
      #restart: on-failure:5
    networks:
      - autocon-workshop
    # Set your hostname to the FQDN under which your
    # sattelites will reach this container
    hostname: icinga2
    env_file:
      - secrets_sql.env
    environment:
      - ICINGA2_FEATURE_GRAPHITE=0
      # Important:
      # keep the hostname graphite the same as
      # the name of the graphite docker-container
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      # put these in secrets_sql.env
      #- NETBOX_URL=http://netbox/api
      #- NETBOX_APIKEY=1234567890
      # - ICINGA2_FEATURE_GRAPHITE_SEND_THRESHOLDS=true
      # - ICINGA2_FEATURE_GRAPHITE_SEND_METADATA=false
      - ICINGAWEB2_ADMIN_USER=icingaadmin
      - ICINGAWEB2_ADMIN_PASS=icinga
      #- ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
      - DEFAULT_MYSQL_HOST=localhost
      # Sending e-mail
      # Sol1 has setup a gmail account just for this image to send notifications from
      # This account's password may be changed occasionally, so please reach out to:
      # icinga@sol1.com.au for an up to date app password
      - GMAIL_SMTP_PASSWORD=dupz ofmo bjyc lfku
    volumes:
      - ./data/icinga/cache:/var/cache/icinga2
      - ./data/icinga/certs:/etc/apache2/ssl
      - ./data/icinga/etc/icinga2:/etc/icinga2
      - ./data/icinga/etc/icingaweb2:/etc/icingaweb2
      - ./data/icinga/etc/icingadb:/etc/icingadb
      - ./data/icinga/lib/icinga:/var/lib/icinga2
      - ./data/icinga/lib/php/sessions:/var/lib/php/sessions
      - ./data/icinga/log/apache2:/var/log/apache2
      - ./data/icinga/log/icinga2:/var/log/icinga2
      - ./data/icinga/log/icingaweb2:/var/log/icingaweb2
      - ./data/icinga/log/mysql:/var/log/mysql
      - ./data/icinga/spool:/var/spool/icinga2
      - ./data/icinga/cron.d/icinga:/etc/cron.d/icinga
      - ./data/icinga/lib/mysql:/var/lib/mysql
    ports:
      - "${ICINGA_PORT}:80"
      - "5665:5665"
      - "8888:8888"

networks:
  autocon-workshop:
    external: true
