#!/bin/bash

sleep 20 && /usr/sbin/icingadb --config /etc/icingadb/config.yml &

# Allow any signal which would kill a process to stop server
trap "pkill --f icingadb" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u root -f icingadb > /dev/null; do sleep 5; done

