#!/bin/bash

sleep 20 && /opt/sol1/meerkat/meerkat --config /opt/sol1/meerkat/meerkat.toml &

# Allow any signal which would kill a process to stop server
trap "pkill --f meerkat" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u root -f meerkat > /dev/null; do sleep 5; done

