#!/bin/bash

echo "sleeping for a while to let is startup"
sleep 20

if icingacli director importsource list | grep -q -E '[0-9]+'; then
    echo "Import sources already exist. Skipping basket import."
else
    echo "No existing import sources found. Proceeding with basket import."



	echo "deploying existing config"
    icingacli director config deploy


    # Change directory to the Icinga baskets folder
    cd /usr/share/icingaweb2/modules/netbox/doc/baskets || exit

    # Create the temporary directory
    mkdir -p /tmp/basket-import

    # Loop through all JSON files in the current directory
    for file in *.json; do
		# we dont want an icinga cluster in this stack
	    if [[ "$file" == "endpoints-automation.json" ]]; then
        continue
    	fi

        # Use sed to replace the baseurl value and copy the result to /tmp/basket-import
        sed "s|\"baseurl\": \".*\"|\"baseurl\": \"${NETBOX_URL}\"|" "$file" | \
        sed "s|\"apitoken\": \".*\"|\"apitoken\": \"${NETBOX_APIKEY}\"|" > "/tmp/basket-import/$file"

        # Run the Icinga Director basket restore command
        icingacli director basket restore < "/tmp/basket-import/$file"

    done

    mkdir -p /tmp/basket-import-extra
    cd /opt/baskets
    for file in *.json; do
        # Use sed to replace the baseurl value and copy the result to /tmp/basket-import
        sed "s|\"baseurl\": \".*\"|\"baseurl\": \"${NETBOX_URL}\"|" "$file" | \
        sed "s|\"apitoken\": \".*\"|\"apitoken\": \"${NETBOX_APIKEY}\"|" > "/tmp/basket-import-extra/$file"

        # Run the Icinga Director basket restore command
		echo "restoring extra baskets"
        icingacli director basket restore < "/tmp/basket-import-extra/$file"
    done



    echo "Basket import completed."

fi

