#!/bin/bash

echo "sleeping for a while to let is startup"
sleep 20

# config gmail password for sending emails
sed -i -e "s|%%GMAILSMTPPASSWORD%%|${GMAIL_SMTP_PASSWORD}|" /etc/msmtprc 

sed -i -e "s|root@localhost|sol1icinga@gmail.com|" /etc/icinga2/conf.d/users.conf


if icingacli director importsource list | grep -q -E '[0-9]+'; then
    echo "Import sources already exist. Skipping basket import."
else
    echo "No existing import sources found. Proceeding with basket import."



	echo "deploying existing config"
    icingacli director config deploy


    # Change directory to the Icinga baskets folder
    cd /usr/share/icingaweb2/modules/netbox/doc/baskets || exit

    # Create the temporary directory
    mkdir -p /tmp/basket-import

    # Loop through all JSON files in the current directory
    for file in *.json; do
		# we dont want an icinga cluster in this stack
	    if [[ "$file" == "endpoints-automation.json" ]]; then
        continue
    	fi

        # Use sed to replace the baseurl value and copy the result to /tmp/basket-import
        sed "s|\"baseurl\": \".*\"|\"baseurl\": \"${NETBOX_URL}/api\"|" "$file" | \
        sed "s|\"apitoken\": \".*\"|\"apitoken\": \"${NETBOX_APIKEY}\"|" > "/tmp/basket-import/$file"

        # Run the Icinga Director basket restore command
        icingacli director basket restore < "/tmp/basket-import/$file"

    done

    mkdir -p /tmp/basket-import-extra
    cd /opt/baskets
    for file in *.json; do
        # Use sed to replace the baseurl value and copy the result to /tmp/basket-import
        sed "s|\"baseurl\": \".*\"|\"baseurl\": \"${NETBOX_URL}/api\"|" "$file" | \
        sed "s|\"apitoken\": \".*\"|\"apitoken\": \"${NETBOX_APIKEY}\"|" > "/tmp/basket-import-extra/$file"

        # Run the Icinga Director basket restore command
		echo "restoring extra baskets"
        icingacli director basket restore < "/tmp/basket-import-extra/$file"
    done

	# notifications baskets commands
    mkdir -p /tmp/basket-import-notifications
    cd /opt/sol1/notifications/director_baskets
    for file in *.json; do
		echo "restoring notification baskets"
        icingacli director basket restore < "$file"
    done

	echo "configuring notification scripts"
	mkdir -p /etc/icinga2/scripts/config/
	sed -e "s/\"from_address\": \".*\"/\"from_address\": \"sol1icinga@gmail.com\"/" \
    -e "s|\"url\": \"http://icinga.domain.local/icingaweb2\"|\"url\": \"http://${MY_EXTERNAL_IP}:${ICINGA_PORT}/icingaweb2\"|" \
    -e "s|\"url\": \"\"|\"url\": \"${NETBOX_URL}\"|" \
    -e "s|\"token\": \"abcdefghijklmnopqrstuvwxyz1234567890\"|\"token\": \"${NETBOX_APIKEY}\"|" \
    /opt/sol1/notifications/src/config/enhanced-mail-notification.json > /etc/icinga2/scripts/config/enhanced-mail-notification.json



    echo "Basket import completed."

fi

